/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Lab3;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Admin
 */
public class QuanLySinhVien extends javax.swing.JFrame {

    List<Student> students = new ArrayList<>();

    /**
     * Creates new form Bai1
     */
    public QuanLySinhVien() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfHoVaTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfDiem = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tfHocLuc = new javax.swing.JTextField();
        chkPhanThuong = new javax.swing.JCheckBox();
        btnThem = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnCapNhat = new javax.swing.JButton();
        btnNhapMoi = new javax.swing.JButton();
        CbbNghanh = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        StudentTable = new javax.swing.JTable();
        btnSXTheoTen = new javax.swing.JButton();
        btnSXTheoDiem = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        jLabel2.setText("HỌ VÀ TÊN");

        jLabel3.setText("ĐIỂM");

        tfDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDiemActionPerformed(evt);
            }
        });
        tfDiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDiemKeyTyped(evt);
            }
        });

        jLabel4.setText("HỌC LỰC");

        jLabel5.setText("NGHÀNH");

        tfHocLuc.setEditable(false);
        tfHocLuc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHocLucActionPerformed(evt);
            }
        });

        chkPhanThuong.setText("Có Phần Thưởng ?");
        chkPhanThuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkPhanThuongActionPerformed(evt);
            }
        });

        btnThem.setText("THÊM");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnXoa.setText("XÓA");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnCapNhat.setText("CẬP NHẬT");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnNhapMoi.setText("NHẬP MỚI");

        CbbNghanh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lập Trình Java", "Lập Trình Rust", "Lập Trình Assembly", "Lập Trình GoLang" }));

        StudentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "HỌ VÀ TÊN", "ĐIỂM", "NGHÀNH", "HỌC LỰC", "THƯỞNG"
            }
        ));
        StudentTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StudentTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(StudentTable);

        btnSXTheoTen.setText("Sắp Xếp Theo Tên ");
        btnSXTheoTen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXTheoTenActionPerformed(evt);
            }
        });

        btnSXTheoDiem.setText("Sắp Xăp Theo Điểm");
        btnSXTheoDiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSXTheoDiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(tfHoVaTen))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(tfDiem))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfHocLuc)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(chkPhanThuong)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnThem)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnXoa)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnCapNhat)
                                                .addGap(18, 18, 18)
                                                .addComponent(btnNhapMoi))
                                            .addComponent(CbbNghanh, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 122, Short.MAX_VALUE)))))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(185, 185, 185))))
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(btnSXTheoTen)
                .addGap(18, 18, 18)
                .addComponent(btnSXTheoDiem)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel2, jLabel3, jLabel4, jLabel5});

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCapNhat, btnNhapMoi, btnThem, btnXoa});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfHoVaTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(CbbNghanh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfHocLuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkPhanThuong)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnNhapMoi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSXTheoTen)
                    .addComponent(btnSXTheoDiem))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkPhanThuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkPhanThuongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkPhanThuongActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        this.addStudent();
        this.fillToTable();
    }//GEN-LAST:event_btnThemActionPerformed

    private void StudentTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StudentTableMouseClicked
        // TODO add your handling code here:
        this.showDetail();
    }//GEN-LAST:event_StudentTableMouseClicked

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        this.removeStudent();
        this.fillToTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnSXTheoTenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXTheoTenActionPerformed
        // TODO add your handling code here:
        this.orderByName();
        this.fillToTable();
    }//GEN-LAST:event_btnSXTheoTenActionPerformed

    private void btnSXTheoDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSXTheoDiemActionPerformed
        // TODO add your handling code here:
        this.orderByMarks();
        this.fillToTable();
    }//GEN-LAST:event_btnSXTheoDiemActionPerformed

    private void tfDiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDiemActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tfDiemActionPerformed

    private void tfHocLucActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHocLucActionPerformed
        // TODO add your handling code here:
        setEnabled(false);
       
    }//GEN-LAST:event_tfHocLucActionPerformed

    private void tfDiemKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDiemKeyTyped
        // TODO add your handling code here:
        char d = evt.getKeyChar();
        if (!Character.isDigit(d)) {
            evt.consume();
        }
        if(tfDiem.getText().length() >= 2){
            evt.consume();
        }
    }//GEN-LAST:event_tfDiemKeyTyped

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        this.updateStudent();
        this.fillToTable();
        
    }//GEN-LAST:event_btnCapNhatActionPerformed
    public void addStudent() {
        Student s = new Student();
        if(tfHoVaTen.getText().equalsIgnoreCase("") && 
                tfDiem.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Không nên để trống");
            return;
        }
        s.name = tfHoVaTen.getText();
        s.marks = Double.parseDouble(tfDiem.getText());
        s.major = (String) CbbNghanh.getSelectedItem();
        students.add(s);
        tfHocLuc.setText(s.getGrade());
        chkPhanThuong.setSelected(s.isBonus());
    }

    public void removeStudent() {
        int Index = StudentTable.getSelectedRow();
        if (Index == -1) {
            return;
        }
        students.remove(Index);
    }

    public void updateStudent() {
        int Index = StudentTable.getSelectedRow();
        if (Index == -1) {
            return;
        }
        if(tfHoVaTen.getText().equalsIgnoreCase("") && 
                tfDiem.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Không nên để trống");
            return;
        }
        if(tfHoVaTen.getText().equalsIgnoreCase("") && 
                tfDiem.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "Không nên để trống");
            return;
        }
        for(var student : students){
                if(student.getName().equals(tfHoVaTen.getText())){
                    student.setName(tfHoVaTen.getText());
                    student.setMajor((String) CbbNghanh.getSelectedItem());
                    student.setMarks(Double.parseDouble(tfDiem.getText()));
                    
                    break;
                }
            }
    }

    public void fillToTable() {
        DefaultTableModel defaultTableModel = (DefaultTableModel) StudentTable.getModel();
        defaultTableModel.setRowCount(0);
        for (Student student : students) {
            Object[] rows = new Object[]{
                student.name, student.marks, student.major, student.getGrade(), student.isBonus()};
            defaultTableModel.addRow(rows);
        }
    }

    public void showDetail() {
        int index = StudentTable.getSelectedRow();
        
        if(index >= 0){
            String stu = (String)StudentTable.getValueAt(index,0);
            for(var student : students){
                if(stu.equals(student.getName())){
                    tfHoVaTen.setText(student.getName());
                    tfHocLuc.setText(student.getGrade());
                    tfDiem.setText(""+student.getMarks());
                    CbbNghanh.setSelectedItem(student.getMajor());
                    chkPhanThuong.setSelected(student.isBonus());
                    break;
                }
            }
        }
    }

    public void orderByName() {
        Comparator<Student> comparator = new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
                return o1.name.compareTo(o2.name);
            }
        };
        Collections.sort(students,comparator);
    }

    public void orderByMarks() {
        Comparator<Student> c = new Comparator<Student>() {
            @Override
            public int compare(Student o1, Student o2) {
               Double d1 = o1.marks;
               Double d2 = o2.marks;
               return d1.compareTo(d2);
            }
        };
        Collections.sort(students,c);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLySinhVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLySinhVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CbbNghanh;
    private javax.swing.JTable StudentTable;
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnNhapMoi;
    private javax.swing.JButton btnSXTheoDiem;
    private javax.swing.JButton btnSXTheoTen;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnXoa;
    private javax.swing.JCheckBox chkPhanThuong;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField tfDiem;
    private javax.swing.JTextField tfHoVaTen;
    private javax.swing.JTextField tfHocLuc;
    // End of variables declaration//GEN-END:variables
}
